# Discord bot for the TU Delft Aerospace Engineering Python course
# Copyright (C) 2020 Delft University of Technology

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public
# License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions For more information see:

name: EduBot CI/CD Pipeline

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing Package and Dependencies
      # All dependencies have to be specified in setup.cfg!
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Linting/Style Checking with Flake8 (Black, isort, docstrings)
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --statistics
    - name: Unit Testing with Pytest
      run: |
        pip install pytest
        pytest
    - name: Code Coverage Analysis
      run: |
        coverage report --fail-under=90

